backend/controllers/AuthController.php
<?php


namespace backend\controllers;


use core\forms\auth\LoginForm;
use core\useCases\auth\AuthService;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AuthController extends Controller
{
    public $layout = 'login';
    /**
     * @var AuthService
     */
    private $authService;


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function __construct($id, $module, AuthService $authService, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->authService = $authService;
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $form = new LoginForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $user = $this->authService->auth($form);
                Yii::$app->user->login($user, $form->rememberMe ? 3600 * 24 * 30 : 0);
                return $this->goBack();
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('login', [
            'model' => $form
        ]);

    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/controllers/BannerController.php
<?php


namespace backend\controllers;


use backend\forms\NewsSearch;
use core\entities\Banners;
use core\entities\News;
use core\forms\manage\BannersForm;
use core\forms\manage\NewsForm;
use core\useCases\manage\NewsManageService;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BannerController extends Controller
{
    /**
     * @var NewsManageService
     */
    private $service;

    public function __construct($id, $module, NewsManageService $service, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    public function actionIndex()
    {
        $model = new Banners();

        $bannersList = [
            1 => Banners::findOne(['number' => 1]),
            2 => Banners::findOne(['number' => 2]),
            41 => Banners::findOne(['number' => 41]),
            42 => Banners::findOne(['number' => 42]),
            43 => Banners::findOne(['number' => 43]),
            44 => Banners::findOne(['number' => 44]),
            7 => Banners::findOne(['number' => 7]),
        ];

        return $this->render('index', [
            'model' => $model,
            'bannersList' => $bannersList,
        ]);
    }

    public function actionCreate()
    {
        $form = new BannersForm();
        $this->layout = 'inner';
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $banners = Banners::create($form->text, 1, $form->image->imageFile);
                $banners->save();
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionUpdate($id)
    {
        $form = new BannersForm($this->findModel($id));
        $this->layout = 'inner';
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $model = $this->findModel($id);
                $model->edit($form->text, $form->image->imageFile);
                $model->save();
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('update', [
            'model' => $form,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Banners::findOne(['number' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/ProfileController.php
<?php


namespace backend\controllers;

use core\forms\manage\User\ProfileForm;
use core\forms\manage\User\SelfProfileForm;
use core\readRepositories\UserReadRepository;
use core\repositories\User\ProfileRepository;
use core\repositories\User\UserRepository;
use core\services\Bitrix24\BitrixApi;
use core\useCases\manage\UserManageService;
use Yii;
use yii\debug\models\search\User;
use yii\web\Controller;

class ProfileController extends Controller
{
    /**
     * @var UserManageService
     */
    private $service;
    /**
     * @var UserReadRepository
     */
    private $repository;
    /**
     * @var BitrixApi
     */
    private $bitrixApi;
    /**
     * @var UserRepository
     */
    private $userRepository;

    public function __construct($id, $module,
                                UserManageService $service,
                                ProfileRepository $repository,
                                UserRepository $userRepository,
                                BitrixApi $bitrixApi,
                                $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
        $this->repository = $repository;
        $this->bitrixApi = $bitrixApi;
        $this->userRepository = $userRepository;
    }

    public function actionUpdate()
    {
        $id = $this->userRepository->get(Yii::$app->user->id)->bitrix_id;
        $form = new SelfProfileForm($this->repository->getOperator($id));
        $this->layout = 'inner';

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->service->editProfile($id, $form);
                return $this->redirect(['/']);
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }
}

backend/views/layouts/inner.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=1500">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrapper">
    <div class="inner-top">
        <a href="<?= $this->params['backUrl'] ?? '/'?>" class="go-back"></a>
        <span class="inner-top__title"><?= $this->title ?></span>
    </div>
    <?= $content ?>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=1500">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Menu;

AppAsset::register($this);
$cookie = $_COOKIE;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=1500">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body <?= (isset($cookie['collapse']) && $cookie['collapse'] === 'true') ? 'class = "sidebar-collapse"' : ''?>>
<?php $this->beginBody() ?>

<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <a href="/" class="i-mini-logo">
            <img src="<?= Url::to('@web/img/mini-logo.svg')?>" alt="" class="i-mini-logo__img">
        </a>
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link burger-menu-link" data-widget="pushmenu" href="#"><span class="burger-menu"></span></a>
            </li>
        </ul>
        <!-- Right navbar links -->
        <ul class="navbar-nav align-items-center ml-auto">
            <li class="nav-item top-nav-item">
                    <?= Html::a('<span class="top-menu-link__img" style="background-image: url('.Url::to('@web/img/exit.svg').')"></span>', ['/auth/logout'], [
                        'class' => 'top-menu-link',
                        'data' => [
                            'confirm' => 'Вы действительно хотите выйти?',
                            'method' => 'post',
                        ],
                    ])?>
            </li>
            <li class="nav-item top-nav-item">
                <a class="top-menu-link top-menu-link--avatar" href="<?= Url::to('/profile/update') ?>">
                    <span class="top-menu-link__img person" style="background-image: url(<?= Url::to('@web/img/person.svg')?>)"></span>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar i-sidebar">
        <!-- Brand Logo -->
        <a href="/" class="brand-link i-brand">
            <img src="<?= Url::to('@web/img/logo-sidebar.svg')?>" alt="" class="brand-image i-brand__img">
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav>
                <?= Menu::widget([
                    'items' => [
                        [
                            'label' => 'Новости и акции',
                            'url' => ['/news'],
                            'active' => in_array($this->context->route,['news/index']),
                            'template' => '<a href="{url}" class="nav-link i-nav-link">
                                                <span class="menu-icon" style="background-image: url('. Url::to('@web/img/sales.svg').')"></span>
                                                <span class="menu-text">
                                                    {label}
                                                </span>
                                            </a>'
                        ],
                        [
                            'label' => 'Рассылки',
                            'url' => ['/dispatch'],
                            'active' => in_array($this->context->route,['dispatch/index']),
                            'template' => '<a href="{url}" class="nav-link i-nav-link">
                                                <span class="menu-icon" style="background-image: url('. Url::to('@web/img/map.svg').')"></span>
                                                <span class="menu-text">
                                                    {label}
                                                </span>
                                            </a>'
                        ],
                        [
                            'label' => 'База пользователей',
                            'url' => ['/user'],
                            'active' => in_array($this->context->route,['user/index']),
                            'template' => '<a href="{url}" class="nav-link i-nav-link">
                                                <span class="menu-icon" style="background-image: url('. Url::to('@web/img/users.svg').')"></span>
                                                <span class="menu-text">
                                                    {label}
                                                </span>
                                            </a>'
                        ],
                        [
                            'label' => 'Карты участков',
                            'url' => ['/land/info'],
                            'active' => in_array($this->context->route,['land/info/index']),
                            'template' => '<a href="{url}" class="nav-link i-nav-link">
                                                <span class="menu-icon" style="background-image: url('. Url::to('@web/img/map-menu.svg').')"></span>
                                                <span class="menu-text">
                                                    {label}
                                                </span>
                                            </a>'
                        ],
                        [
                            'label' => 'Баннеры',
                            'url' => ['/banner/index'],
                            'active' => in_array($this->context->route,['banner/index']),
                            'template' => '<a href="{url}" class="nav-link i-nav-link">
                                                <span class="menu-icon" style="background-image: url('. Url::to('@web/img/banner.svg').')"></span>
                                                <span class="menu-text">
                                                    {label}
                                                </span>
                                            </a>'
                        ],
                    ],
                    'itemOptions' => [
                        'class' => 'nav-item'
                    ],
                    'options' => [
                        'class' => 'nav nav-pills nav-sidebar flex-column',
                        'data-widget' => 'treeview',
                        'data-accordion' => 'false',
                    ],
                    'activeCssClass'=>'active'
                ])?>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
            <?= $content ?>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>