backend/controllers/CatalogController.php
<?php


namespace backend\controllers;


use backend\forms\CatalogSearch;
use Yii;
use yii\web\Controller;

class CatalogController extends Controller
{
    public $layout = 'inner';

    public function actionIndex($land_id, $point_id)
    {
        $searchModel = new CatalogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'landId' => $land_id,
            'point_id' => $point_id
        ]);
    }
}

backend/views/land/editor/_catalog.php
<?
use core\entities\Catalog\Catalog;
use yii\helpers\Url;

/* @var $this \yii\web\View
 *  @var $catalog Catalog
 */
?>

<div id="editor-info">
    <div class="editor-info__section">
        <div class="editor-info__img-wrap-outer">
            <div class="editor-info__img-wrap">
                <img src="<?= ($catalog->image ? $catalog->getUploadUrl('image') : Url::to('@static/default.png')) ?>" alt="" class="editor-info__img">
            </div>
        </div>
    </div>
    <span class="editor-info__title"><?= $catalog->title ?></span>
        <? if ($catalog->features) : ?>
            <ul class="features">
                <?php foreach($catalog->features as $feature):?>
                    <li class="features__item">
                        <span class="features__title"><?= $feature->name ?></span> <?= $feature->value ?>
                    </li>
                <?php endforeach;?>
            </ul>
        <? endif;?>
        <? if ($catalog->rels) : ?>
            <div class="garden-relations editor-info__section">
                <span class="garden-relations__title">Аналоги <?= $catalog->title ?>
                </span>
                <div class="row">
                    <? $i = 0;  foreach($catalog->rels as $rel) : if (empty($rel->catalog)) continue; $i++?>
                        <div class="col-6">
                            <div class="cart">
                                <div class="cart__img-wrap-outer">
                                    <div class="cart__img-wrap">
                                        <img src="<?= ($rel->catalog->image ? $rel->catalog->getUploadUrl('image') : Url::to('@static/default.png')) ?>" alt="" class="cart__img">
                                    </div>
                                </div>
                                <p class="cart__title">
                                    <?= $rel->catalog->title ?>
                                </p>
                            </div>
                        </div>
                    <? if ($i >= 2) break; endforeach;?>
                </div>
            </div>
        <? endif;?>
</div>

backend/views/land/editor/_info.php
<?
/* @var $this \yii\web\View
 * @var $gardenInfoModel GardenInfoForm
 * @var $pointInfo GardenInfo
 * @var $pointId integer
 *  @var $catalog Catalog
 * @var $model Land
 */

use core\entities\Catalog\Catalog;
use core\entities\Land\Garden\GardenInfo;
use core\entities\Land\Land;
use core\forms\manage\Land\GardenInfoForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
        'options' => ['class' => 'editor-info'],
        'action' => Url::to(['land/editor/garden', 'id' => $model->id])
    ])?>
    <div class="editor-info__top">
        <span class="editor-info__title">Общая информация о растении</span>
        <a href="<?= Url::to(['catalog/index', 'land_id' => $model->id, 'point_id' => $pointId])?>" class="editor-info__nav"><?= $catalog ? 'Выбрать другое растение' : 'Выбрать из каталога'?></a>
    </div>
    <p class="editor-info__txt">Выберите растение из каталога, чтобы увидеть информацию</p>
    <? if ($catalog) echo $this->render('_catalog', ['catalog' => $catalog]) ?>
    <div class="editor-info__section">
        <span class="editor-info__title mb16">Информация по данному растению</span>
        <div class="row">
            <div class="col-6">
                <?= $form->field($gardenInfoModel, 'landing_date')->textInput([
                    'class' => 'form-control date',
                    'maxlength' => true,
                    'placeholder' => 'дд.мм.гггг',
                    'value' => $gardenInfoModel->landing_date ? (new DateTime($gardenInfoModel->landing_date))->format('d.m.Y') : '',
                ]) ?>
            </div>
        </div>
    </div>
    <div class="editor-info__section">
        <span class="editor-info__title mb18">Персональные рекомендации по уходу</span>
        <?= $form->field($gardenInfoModel, 'text', [
            'template' => '{input}{hint}'
        ])->textarea([
            'maxlength' => true,
            'rows' => 5,
            'class' => 'form-control textarea',
            'placeholder' => 'Персональные рекомендации по уходу'
        ]) ?>
    </div>
    <?= $form->field($gardenInfoModel, 'land_points_id', ['template' => '{input}'])->hiddenInput(['value' => $pointId])?>
    <? if ($catalog) echo  $form->field($gardenInfoModel, 'catalog_id', ['template' => '{input}'])->hiddenInput(['value' => $catalog->id])?>
    <div class="row">
        <div class="col-6">
            <?= Html::submitButton('Сохранить и продолжить', ['class' => 'btn btn-block btn-default btn-red']) ?>
        </div>
        <div class="col-6">
            <?php if ($catalog) : ?>
                <button type="button" id="cancel" class="btn btn-block btn-default">Отменить изменения</button>
            <?php endif; ?>
        </div>
    </div>
<? ActiveForm::end() ?>

backend/views/land/editor/garden.php
<?php

use core\entities\Catalog\Catalog;
use core\forms\manage\Land\GardenInfoForm;
use yii\helpers\Json;
use yii\helpers\Url;

/* @var $this \yii\web\View
 * @var $points array
 * @var $gardenInfoModel GardenInfoForm
 * @var $pointId integer
 * @var $catalog Catalog
 */
$this->title = 'Добавление участка';
$this->params['backUrl'] = Url::to(['/land/editor/points', 'id' => $model->id]);
$imageSize = $model->map->getImageSize();
$imageWrapStyle = '';
if (!empty($imageSize) && is_array($imageSize)) {
    $imageWrapStyle = sprintf('style="width:%dpx"', $imageSize['width']);
}
?>
<script>
    <?= $points ? 'var points = '. Json::encode(array_map(function ($item) use($model) {
            $item['link'] = (isset($item['link']) && $item['link']) ? Url::to(['land/editor/garden', 'id' => $model->id, 'point_id' => $item['id']]) : false;
            return $item;
        }, $points)) : '' ?>
</script>
<div class="inner-content">
    <div class="top-spike">
        <div class="steps">
            <a href="<?= $this->params['backUrl'] ?>" class="steps__item"><span>Шаг 1 «Создание участка»</span></a>
            <span class="steps__item active">Шаг 2 «Добавление растений»</span>
        </div>
        <div class="next-btn-wrap">
            <a href="<?= Url::to(['land/info'])?>" class="btn btn-block btn-default btn-red next-btn">Готово</a>
        </div>
    </div>
    <div class="select-editor">
        <div class="select-editor__left">
            <div class="resize-indicator-container">
                           <span class="resize-indicator resize-indicator--vertical">
                               <span class="resize-indicator__fill"></span>
                               <span class="resize-indicator__round"></span>
                           </span>
                <span class="resize-indicator resize-indicator--horizontal">
                               <span class="resize-indicator__fill"></span>
                               <span class="resize-indicator__round"></span>
                           </span>
                <div class="workbench-container__outer">
                    <div class="workbench-container__inner" <?= $imageWrapStyle ?>>
                        <img src="<?= $model->map->getUploadUrl('image') ?>" class="image" alt="">
                        <div id="workbench" class="workbench dropzone"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="select-editor__right">
            <div class="editor-info-wrap">
                <? if ($pointId) {
                        echo $this->render('_info', [
                            'model' => $model,
                            'gardenInfoModel' => $gardenInfoModel,
                            'pointId' => $pointId,
                            'catalog' => $catalog
                        ]);
                    } else {
                        echo  '<div class="editor-info__top">
                                    <span class="editor-info__title">Выберите растение на карте для редактирования информации</span>
                                </div>';
                    }

                ?>
            </div>
        </div>
    </div>
</div>

backend/views/land/editor/paint.php
<?php
/* @var $this \yii\web\View */

use yii\helpers\Url;

$this->title = 'Добавление участка';
$this->params['backUrl'] = Url::to(['/land/info']);
?>
<script>
    var saveUrl = '<?= Url::to(Url::to(['/land/editor/paint-save', 'id' => $model->id]))?>'
</script>
<div class="inner-content">
    <div class="top-spike">
        <div class="steps">
            <span class="steps__item active">Шаг 1 «Создание участка»</span>
            <a href="<?= Url::to(['/land/editor/points', 'id' => $model->id]) ?>" class="steps__item"><span>Шаг 2 «Добавление растений»</span></a>
        </div>
        <div class="next-btn-wrap">
            <a href="<?= Url::to(['land/editor/points', 'id' => $model->id]) ?>" class="btn btn-block btn-default btn-red next-btn">Далее</a>
        </div>
    </div>
    <script>
    <?= isset($model->map) ? "var img = '".$model->map->getUploadUrl('image')."';" : '' ?>
    </script>
    <div class="editor-content">
        <div id="editor" class="editor"></div>
    </div>
</div>

backend/views/land/editor/points.php
<?php

use yii\helpers\Json;
use yii\helpers\Url;

/* @var $this \yii\web\View
 * @var $gardens Garden[][]
 * @var $points string
 */
$this->title = 'Добавление участка';
$this->params['backUrl'] = Url::to(['/land/editor/paint', 'id' => $model->id]);
$imageSize = $model->map->getImageSize();
$imageWrapStyle = '';
if (!empty($imageSize) && is_array($imageSize)) {
    $imageWrapStyle = sprintf('style="width:%dpx"', $imageSize['width']);
}
?>
<script>
    <?= $points ? 'var points = '. Json::encode($points).';' : '' ?>
    var saveUrl = '<?= Url::to(Url::to(['/land/editor/points-save', 'id' => $model->id]))?>'
</script>
<div class="inner-content">
    <div class="top-spike">
        <div class="steps">
            <a href="<?= $this->params['backUrl'] ?>" class="steps__item"><span>Шаг 1 «Создание участка»</span></a>
            <span class="steps__item active">Шаг 2 «Добавление растений»</span>
        </div>
        <div class="next-btn-wrap">
            <a href="<?= Url::to(['/land/editor/garden', 'id' => $model->id]) ?>" class="btn btn-block btn-default btn-red next-btn">Далее</a>
        </div>
    </div>
    <div class="plants-content">
        <div class="plants-editor">
            <div class="workbench-container">
                <div class="workbench-container__left">
                    <div class="resize-indicator-container">
                           <span class="resize-indicator resize-indicator--vertical">
                               <span class="resize-indicator__fill"></span>
                               <span class="resize-indicator__round"></span>
                           </span>
                        <span class="resize-indicator resize-indicator--horizontal">
                               <span class="resize-indicator__fill"></span>
                               <span class="resize-indicator__round"></span>
                           </span>
                        <div class="workbench-container__outer">
                            <div class="workbench-container__inner" <?= $imageWrapStyle ?>>
                                <img src="<?= $model->map->getUploadUrl('image') ?>" class="image" alt="">
                                <div id="workbench" class="workbench dropzone"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="workbench-container__right">
                    <div class="preview-container">
                        <div class="preview">
                            <span class="preview__title">Виды растений</span>
                            <ul class="preview-list">
                                <? if (is_array($gardens) && !empty($gardens)): ?>
                                    <? foreach($gardens as $gardens_list): ?>
                                        <li class="preview-list__item">
                                            <span class="preview-list__item-title"><?= $gardens_list[0]->category ?></span>
                                            <div class="preview-list__content">
                                                <ul class="plant-list">
                                                    <? foreach($gardens_list as $garden): ?>
                                                        <li class="plant-list__item">
                                                            <div class="preview-prototype-container">
                                                                <div data-id="<?= $garden->id ?>" class="round preview-prototype" style="background-image: url(<?= Yii::getAlias('@static/gardens/'.$garden->image) ?>)"></div>
                                                            </div>
                                                            <span class="plant-list__text"><?= $garden->name ?></span>
                                                        </li>
                                                    <? endforeach; ?>
                                                </ul>
                                            </div>
                                        </li>
                                    <? endforeach; ?>
                                <? endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>